package ru.nsu.fit.g17209.kokunin.task2.graphics;

import javax.swing.*;
import java.awt.*;

public class NewGSetPane extends JPanel {
    private JPanel settingsPanel;
    private JButton startButton;
    private JButton saveButton;
    private JButton loadButton;
    private JButton settingsButton;

    private void createUIComponents() {
        $$$setupUI$$$();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        settingsPanel = new JPanel();
        settingsPanel.setLayout(new GridBagLayout());
        settingsPanel.setAlignmentX(0.25f);
        settingsPanel.setAlignmentY(0.75f);
        settingsPanel.setAutoscrolls(true);
        settingsPanel.setBackground(new Color(-1052262));
        settingsPanel.setDoubleBuffered(true);
        settingsPanel.setForeground(new Color(-12307672));
        settingsPanel.setMaximumSize(new Dimension(120000, 360000));
        settingsPanel.setMinimumSize(new Dimension(120, 360));
        settingsPanel.setPreferredSize(new Dimension(160, 480));
        settingsPanel.setVerifyInputWhenFocusTarget(true);
        settingsPanel.putClientProperty("html.disable", Boolean.FALSE);
        settingsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-12307672)), null));
        saveButton = new JButton();
        saveButton.setBackground(new Color(-1052262));
        saveButton.setText("Save");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        settingsPanel.add(saveButton, gbc);
        loadButton = new JButton();
        loadButton.setBackground(new Color(-1052262));
        loadButton.setText("Load");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        settingsPanel.add(loadButton, gbc);
        settingsButton = new JButton();
        settingsButton.setBackground(new Color(-1052262));
        settingsButton.setText("Settings");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        settingsPanel.add(settingsButton, gbc);
        startButton = new JButton();
        startButton.setBackground(new Color(-1052262));
        startButton.setText("Start");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        settingsPanel.add(startButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return settingsPanel;
    }

}
